#!/usr/bin/env bash
# scripts/release.sh
#
# One-command release flow for claude-autopilot. Orchestrates the mechanical
# steps that were done by hand for v0.6.0 (and easy to get wrong):
#
#   1. Validate target version (semver, > current).
#   2. Verify clean working tree on main.
#   3. Run bats tests; capture green count.
#   4. Update README test count + plugin.json version.
#   5. Build a draft changelog from `git log <prev-tag>..HEAD` filtered to PR merges.
#   6. Open $EDITOR on the tag annotation (skip with --no-edit).
#   7. Commit, tag, push, gh release create.
#
# Pure helpers live in lib/release-utils.sh; this file is the side-effecting
# orchestrator.
#
# Usage:
#   scripts/release.sh <version> [--dry-run] [--no-edit]
#
# Flags:
#   --dry-run   Print every planned action; don't mutate files, git, or gh.
#   --no-edit   Skip the $EDITOR step; use the autogenerated changelog as-is.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/release-utils.sh
source "$PLUGIN_ROOT/lib/release-utils.sh"

# ---------- arg parsing ----------

TARGET_VERSION=""
DRY_RUN=0
NO_EDIT=0

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --no-edit) NO_EDIT=1 ;;
    --*) echo "ERROR: unknown flag: $arg" >&2; exit 2 ;;
    *)
      if [ -z "$TARGET_VERSION" ]; then
        TARGET_VERSION="$arg"
      else
        echo "ERROR: unexpected positional arg: $arg" >&2
        exit 2
      fi
      ;;
  esac
done

if [ -z "$TARGET_VERSION" ]; then
  echo "ERROR: missing target version argument" >&2
  echo "usage: scripts/release.sh <version> [--dry-run] [--no-edit]" >&2
  exit 2
fi

if ! validate_version_format "$TARGET_VERSION"; then
  echo "ERROR: invalid version format: '$TARGET_VERSION' (expected MAJOR.MINOR.PATCH, no prefix, no suffix)" >&2
  exit 2
fi

# ---------- preconditions ----------

current_branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$current_branch" != "main" ]; then
  echo "ERROR: must be on main branch (currently on '$current_branch')" >&2
  exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree is not clean. Commit or stash changes first." >&2
  git status --short >&2
  exit 1
fi

PLUGIN_JSON="$PLUGIN_ROOT/.claude-plugin/plugin.json"
README_MD="$PLUGIN_ROOT/README.md"

current_version="$(grep -E '"version":[[:space:]]*"[^"]*"' "$PLUGIN_JSON" | sed -E 's/.*"version":[[:space:]]*"([^"]*)".*/\1/')"
if [ -z "$current_version" ]; then
  echo "ERROR: could not parse current version from $PLUGIN_JSON" >&2
  exit 1
fi

if ! version_greater_than "$TARGET_VERSION" "$current_version"; then
  echo "ERROR: target version '$TARGET_VERSION' is not greater than current '$current_version'" >&2
  exit 1
fi

echo "Releasing claude-autopilot $current_version -> $TARGET_VERSION"
[ "$DRY_RUN" -eq 1 ] && echo "(dry-run mode: no files or remote will be modified)"

# ---------- run tests, capture green count ----------

echo "Running bats tests..."
if [ "$DRY_RUN" -eq 1 ]; then
  test_count="$(bats tests/lib/ 2>/dev/null | grep -c "^ok " || true)"
else
  test_output="$(bats tests/lib/)"
  if echo "$test_output" | grep -q "^not ok "; then
    echo "ERROR: bats tests failed; aborting release" >&2
    echo "$test_output" >&2
    exit 1
  fi
  test_count="$(echo "$test_output" | grep -c "^ok " || true)"
fi
echo "  green tests: $test_count"

# ---------- build changelog ----------

prev_tag="$(git describe --tags --abbrev=0 2>/dev/null || echo "")"
if [ -n "$prev_tag" ]; then
  raw_log="$(git log "${prev_tag}..HEAD" --format='%s')"
else
  raw_log="$(git log HEAD --format='%s')"
fi
changelog="$(extract_pr_merges_from_log "$raw_log")"

# Build the tag annotation draft.
annotation_file="$(mktemp -t release-annotation.XXXXXX)"
trap 'rm -f "$annotation_file"' EXIT
{
  echo "claude-autopilot v$TARGET_VERSION"
  echo
  echo "Changes since ${prev_tag:-initial}:"
  echo
  if [ -n "$changelog" ]; then
    echo "$changelog" | sed 's/^/- /'
  else
    echo "- (no PR merges detected since previous tag)"
  fi
} > "$annotation_file"

if [ "$DRY_RUN" -eq 1 ]; then
  echo "--- planned changelog ---"
  cat "$annotation_file"
  echo "--- end changelog ---"
  echo "Dry-run complete. No mutations performed."
  exit 0
fi

# ---------- editor pass ----------

if [ "$NO_EDIT" -eq 0 ]; then
  "${EDITOR:-vi}" "$annotation_file"
fi

# ---------- mutate files ----------

readme_content="$(cat "$README_MD")"
new_readme="$(update_readme_test_count "$readme_content" "$test_count")"
echo "$new_readme" > "$README_MD"

plugin_content="$(cat "$PLUGIN_JSON")"
new_plugin="$(update_plugin_version "$plugin_content" "$TARGET_VERSION")"
echo "$new_plugin" > "$PLUGIN_JSON"

# ---------- commit, tag, push, release ----------

git add "$README_MD" "$PLUGIN_JSON"
git commit -m "chore: release v${TARGET_VERSION}"

git tag -a "v${TARGET_VERSION}" -F "$annotation_file"

git push origin main
git push origin "v${TARGET_VERSION}"

gh release create "v${TARGET_VERSION}" --title "v${TARGET_VERSION}" --notes-file "$annotation_file"

echo "Released v${TARGET_VERSION}"
